camunda.bpm.authorization.enabled: true

spring.h2.console.enabled: true  
 
spring.jpa.hibernate.ddl-auto: none 

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.hibernate: ERROR    